# Generated by Django 5.1.4 on 2025-01-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridge',
            options={'managed': False},
        ),
    ]
